Failures in [node-test-pull-request/69796](https://ci.nodejs.org/job/node-test-pull-request/69796/) to [node-test-pull-request/69894](https://ci.nodejs.org/job/node-test-pull-request/69894/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2025-10-27.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2025-10-27 00:12 | 0       | 25      | 23       | 4       | 48      | 26.04%     |


### Jenkins Failure

| Reason | <code>Backing channel 'JNLP4-connect connection from ... is disconnected.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60330/](https://ci.nodejs.org/job/node-test-pull-request/69842/), [https://github.com/nodejs/node/pull/60331/](https://ci.nodejs.org/job/node-test-pull-request/69843/)) |
| Appeared | [test-digitalocean-ubuntu2404-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=ubuntu2404-x64/67067/console), [test-digitalocean-ubuntu2404-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=ubuntu2404-x64/67066/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69842/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69843/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=ubuntu2404-x64/67067/console">Example</a></summary>

```
java.io.IOException: Backing channel 'JNLP4-connect connection from 167.99.124.188/167.99.124.188:48116' is disconnected.
	at hudson.remoting.RemoteInvocationHandler.channelOrFail(RemoteInvocationHandler.java:227)
	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:306)
	at jdk.proxy2/jdk.proxy2.$Proxy105.isAlive(Unknown Source)
	at hudson.Launcher$RemoteLauncher$ProcImpl.isAlive(Launcher.java:1227)
	at hudson.Launcher$RemoteLauncher$ProcImpl.join(Launcher.java:1219)
```
</details>

-------

| Reason | <code>Build timed out (after 30 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60255/](https://ci.nodejs.org/job/node-test-pull-request/69805/), [https://github.com/nodejs/node/pull/60111/](https://ci.nodejs.org/job/node-test-pull-request/69831/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/37352/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69805/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69831/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/37352/console">Example</a></summary>

```
Build timed out (after 30 minutes). Marking the build as failed.
```
</details>

-------


### Build Failure

| Reason | <code>ERROR: Step ‘Publish JUnit test result report’ failed: no workspace for ...</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 17 ([https://github.com/nodejs/node/pull/60289/](https://ci.nodejs.org/job/node-test-pull-request/69799/), [https://github.com/nodejs/node/pull/60271/](https://ci.nodejs.org/job/node-test-pull-request/69803/), [https://github.com/nodejs/node/pull/60178/](https://ci.nodejs.org/job/node-test-pull-request/69808/), [https://github.com/nodejs/node/pull/60274/](https://ci.nodejs.org/job/node-test-pull-request/69818/), [https://github.com/nodejs/node/pull/60278/](https://ci.nodejs.org/job/node-test-pull-request/69823/), [https://github.com/nodejs/node/pull/59734/](https://ci.nodejs.org/job/node-test-pull-request/69825/), [https://github.com/nodejs/node/pull/60111/](https://ci.nodejs.org/job/node-test-pull-request/69831/), [https://github.com/nodejs/node/pull/60139/](https://ci.nodejs.org/job/node-test-pull-request/69832/), [https://github.com/nodejs/node/pull/59873/](https://ci.nodejs.org/job/node-test-pull-request/69835/), [https://github.com/nodejs/node/pull/60248/](https://ci.nodejs.org/job/node-test-pull-request/69841/), [https://github.com/nodejs/node/pull/60330/](https://ci.nodejs.org/job/node-test-pull-request/69842/), [https://github.com/nodejs/node/pull/60331/](https://ci.nodejs.org/job/node-test-pull-request/69843/), [https://github.com/nodejs/node/pull/60367/](https://ci.nodejs.org/job/node-test-pull-request/69856/), [https://github.com/nodejs/node/pull/60413/](https://ci.nodejs.org/job/node-test-pull-request/69882/), [https://github.com/nodejs/node/pull/60390/](https://ci.nodejs.org/job/node-test-pull-request/69883/), [https://github.com/nodejs/node/pull/60190/](https://ci.nodejs.org/job/node-test-pull-request/69888/), [https://github.com/nodejs/node/pull/60391/](https://ci.nodejs.org/job/node-test-pull-request/69889/)) |
| Appeared | [vm-k5d2b](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx15-arm64/66902/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69799/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69889/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx15-arm64/66902/console">Example</a></summary>

```
ERROR: Step ‘Publish JUnit test result report’ failed: no workspace for node-test-commit-osx/nodes=osx15-arm64 #66902
Collecting metadata...
Metadata collection done.
[Checks API] No suitable checks publisher found.
Notifying upstream projects of job completion
Finished: FAILURE
```
</details>

-------

| Reason | <code>fatal: No rebase in progress?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/60255/](https://ci.nodejs.org/job/node-test-pull-request/69805/), [https://github.com/nodejs/node/pull/60289/](https://ci.nodejs.org/job/node-test-pull-request/69809/), [https://github.com/nodejs/node/pull/60298/](https://ci.nodejs.org/job/node-test-pull-request/69810/), [https://github.com/nodejs/node/pull/60331/](https://ci.nodejs.org/job/node-test-pull-request/69843/), [https://github.com/nodejs/node/pull/60281/](https://ci.nodejs.org/job/node-test-pull-request/69847/)) |
| Appeared | [test-digitalocean-ubuntu2404_sharedlibs_container-x64-6](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_shared_x64/53256/console), [test-digitalocean-ubuntu2404_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_shared_x64/53252/console), [test-mnx-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-linter/62233/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69805/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69847/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_shared_x64/53256/console">Example</a></summary>

```
fatal: No rebase in progress?
```
</details>

-------


### JSTest Failure

| Reason | <code>sequential/test-worker-prof</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 7 ([https://github.com/nodejs/node/pull/60266/](https://ci.nodejs.org/job/node-test-pull-request/69796/), [https://github.com/nodejs/node/pull/60289/](https://ci.nodejs.org/job/node-test-pull-request/69814/), [https://github.com/nodejs/node/pull/60274/](https://ci.nodejs.org/job/node-test-pull-request/69818/), [https://github.com/nodejs/node/pull/60364/](https://ci.nodejs.org/job/node-test-pull-request/69858/), [https://github.com/nodejs/node/pull/60390/](https://ci.nodejs.org/job/node-test-pull-request/69879/), [https://github.com/nodejs/node/pull/60391/](https://ci.nodejs.org/job/node-test-pull-request/69887/), [https://github.com/nodejs/node/pull/60419/](https://ci.nodejs.org/job/node-test-pull-request/69890/)) |
| Appeared | [test-azure_msft-win10_vs2019-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2022_clang/37414/console), [vm-qljhz](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67545/console), [test-azure_msft-win10_vs2019-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2022_clang/37402/console), [test-azure_msft-win11_vs2022-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2022_clang/37402/console), [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/52062/console), [test-azure_msft-win10_vs2019-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2022_clang/37332/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69796/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69890/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2022_clang/37414/console">Example</a></summary>

```
not ok 1163 sequential/test-worker-prof
  ---
  duration_ms: 2412.75200
  severity: fail
  exitcode: 1
  stack: |-
    files found in working directory before worker starts [ 'isolate-0000011CC0C6B000-8212-v8.log' ]
    parent prof file: isolate-0000011CC0C6B000-8212-v8.log
    parent posted 45931 messages
    files found in working directory before worker exits [
      'isolate-0000011CC0C6B000-8212-v8.log',
      'isolate-0000011CDA1F5000-8212-v8.log'
    ]
    worker prof file: isolate-0000011CDA1F5000-8212-v8.log
    
    worker ticks 9
    parent ticks 32
    node:internal/assert/utils:146
      throw error;
      ^
    
    AssertionError [ERR_ASSERTION]: worker ticks <= 10:
    tick,0x7ff7559135c1,48894,0,0x0,2,0x7ff7558fca90,0x36f94a51c6b,0x36f94a51912,0x36f94a4f165,0x36f94a4cb21,0x36f94a4c9a7,0x36f94a4c835,0x36f94a4c0d4
    tick,0x7ff75597d1b7,96916,0,0x0,2,0x11c8008297e,0x11c80082607,0x36f94a635c3,0x11c80082a4f,0x11c80082607,0x36f94a52e2e
    tick,0x7ff75597ce90,145043,0,0x0,2,0x11c8008297e,0x11c800...
```
</details>

-------

| Reason | <code>parallel/test-runner-output</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/60266/](https://ci.nodejs.org/job/node-test-pull-request/69796/), [https://github.com/nodejs/node/pull/60274/](https://ci.nodejs.org/job/node-test-pull-request/69818/), [https://github.com/nodejs/node/pull/59873/](https://ci.nodejs.org/job/node-test-pull-request/69835/), [https://github.com/nodejs/node/pull/60334/](https://ci.nodejs.org/job/node-test-pull-request/69838/), [https://github.com/nodejs/node/pull/60190/](https://ci.nodejs.org/job/node-test-pull-request/69888/), [https://github.com/nodejs/node/pull/60391/](https://ci.nodejs.org/job/node-test-pull-request/69889/)) |
| Appeared | [vm-rgwwn](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67543/console), [test-ibm-rhel9-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel9-x64/67060/console), [vm-zn9if](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67483/console), [undefined](https://ci.nodejs.org/job/node-test-commit-custom-suites-freestyle/44458/console), [test-azure_msft-win11_vs2022-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-COMPILED_BY-vs2022_clang/37319/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69796/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69889/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67543/console">Example</a></summary>

```
not ok 3140 parallel/test-runner-output
  ---
  duration_ms: 120142.32600
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    TAP version 13
    # Subtest: test runner output
        # Subtest: test-runner/output/abort.js
        ok 1 - test-runner/output/abort.js
          ---
          duration_ms: 2592.095926
          ...

```
</details>

-------

| Reason | <code>parallel/test-watch-mode-kill-signal-override</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/60298/](https://ci.nodejs.org/job/node-test-pull-request/69810/), [https://github.com/nodejs/node/pull/60139/](https://ci.nodejs.org/job/node-test-pull-request/69832/), [https://github.com/nodejs/node/pull/60318/](https://ci.nodejs.org/job/node-test-pull-request/69860/), [https://github.com/nodejs/node/pull/60372/](https://ci.nodejs.org/job/node-test-pull-request/69871/), [https://github.com/nodejs/node/pull/60190/](https://ci.nodejs.org/job/node-test-pull-request/69888/), [https://github.com/nodejs/node/pull/60391/](https://ci.nodejs.org/job/node-test-pull-request/69889/)) |
| Appeared | [vm-jgrbo](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67547/console), [vm-yinh4](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67546/console), [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/52074/console), [test-azure-ubuntu2204_container-arm64-5](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/60808/console), [vm-usrrc](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67479/console), [test-azure_msft-win10_vs2019-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win10-COMPILED_BY-vs2022_clang/37328/console), [test-azure_msft-win11_vs2022-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-COMPILED_BY-vs2022_clang/37328/console), [test-rackspace-win2019_vs2019-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2019-COMPILED_BY-vs2022_clang/37328/console), [test-rackspace-win2022_vs2022-x64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2022-COMPILED_BY-vs2022_clang/37328/console), [test-azure_msft-win11_vs2022-arm64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/37328/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69810/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69889/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67547/console">Example</a></summary>

```
not ok 4425 parallel/test-watch-mode-kill-signal-override
  ---
  duration_ms: 120094.59500
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-http2-close-while-writing</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/60289/](https://ci.nodejs.org/job/node-test-pull-request/69799/), [https://github.com/nodejs/node/pull/60278/](https://ci.nodejs.org/job/node-test-pull-request/69823/), [https://github.com/nodejs/node/pull/60313/](https://ci.nodejs.org/job/node-test-pull-request/69848/), [https://github.com/nodejs/node/pull/60390/](https://ci.nodejs.org/job/node-test-pull-request/69883/)) |
| Appeared | [vm-wfocy](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67540/console), [test-osuosl-rhel8-ppc64_le-2](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/61216/console), [vm-o2tby](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67468/console), [vm-xrtit](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67444/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69799/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69883/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67540/console">Example</a></summary>

```
not ok 2310 parallel/test-http2-close-while-writing
  ---
  duration_ms: 120092.64800
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-quic-test-client</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/60178/](https://ci.nodejs.org/job/node-test-pull-request/69808/), [https://github.com/nodejs/node/pull/60111/](https://ci.nodejs.org/job/node-test-pull-request/69831/), [https://github.com/nodejs/node/pull/60331/](https://ci.nodejs.org/job/node-test-pull-request/69843/), [https://github.com/nodejs/node/pull/60391/](https://ci.nodejs.org/job/node-test-pull-request/69880/)) |
| Appeared | [vm-z2sho](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67534/console), [vm-q9xx6](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67494/console), [vm-5d9v3](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67478/console), [vm-92kcy](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67452/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69808/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69880/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67534/console">Example</a></summary>

```
not ok 2578 parallel/test-quic-test-client
  ---
  duration_ms: 1443.27800
  severity: fail
  exitcode: 1
  stack: |-
    /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/out/Release/ngtcp2_test_client
    node:internal/modules/run_main:107
        triggerUncaughtException(
        ^
    
    AssertionError [ERR_ASSERTION]: Missing expected rejection.
        at process.processTicksAndRejections (node:internal/process/task_queues:103:5)
        at async file:///Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/parallel/test-quic-test-client.mjs:36:1 {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      actual: undefined,
      expected: { message: /Process exited with code 1 and signal null/ },
      operator: 'rejects',
      diff: 'simple'
    }
    
    Node.js v26.0.0-pre
  ...

```
</details>

-------

| Reason | <code>sequential/test-perf-hooks</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/60289/](https://ci.nodejs.org/job/node-test-pull-request/69799/), [https://github.com/nodejs/node/pull/60248/](https://ci.nodejs.org/job/node-test-pull-request/69841/), [https://github.com/nodejs/node/pull/60330/](https://ci.nodejs.org/job/node-test-pull-request/69842/), [https://github.com/nodejs/node/pull/60331/](https://ci.nodejs.org/job/node-test-pull-request/69843/)) |
| Appeared | [vm-k7hpr](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67492/console), [vm-xrtit](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67444/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69799/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69843/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67492/console">Example</a></summary>

```
not ok 4747 sequential/test-perf-hooks
  ---
  duration_ms: 895.86800
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:77
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: Date.now() - performance.timeOrigin (491.593017578125) - process.uptime() * 1000 (371.23216399999995) = 120.36085357812505 >= +- 50
        at Object.<anonymous> (/Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/sequential/test-perf-hooks.js:36:3)
        at Module._compile (node:internal/modules/cjs/loader:1760:14)
        at Object..js (node:internal/modules/cjs/loader:1893:10)
        at Module.load (node:internal/modules/cjs/loader:1480:32)
        at Module._load (node:internal/modules/cjs/loader:1299:12)
        at TracingChannel.traceSync (node:diagnostics_channel:328:14)
        at wrapModuleLoad (node:internal/modules/cjs/loader:244:24)
        at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
        at node:internal/main/run_main_...
```
</details>

-------

| Reason | <code>parallel/test-runner-watch-mode</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/60111/](https://ci.nodejs.org/job/node-test-pull-request/69831/), [https://github.com/nodejs/node/pull/60139/](https://ci.nodejs.org/job/node-test-pull-request/69832/), [https://github.com/nodejs/node/pull/59873/](https://ci.nodejs.org/job/node-test-pull-request/69835/)) |
| Appeared | [vm-gthqd](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67476/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69831/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69835/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67476/console">Example</a></summary>

```
not ok 2512 parallel/test-runner-watch-mode
  ---
  duration_ms: 12314.16600
  severity: fail
  exitcode: 1
  stack: |-
    TAP version 13
    # Subtest: test runner watch mode
        # Subtest: should run tests repeatedly
        ok 1 - should run tests repeatedly
          ---
          duration_ms: 2034.797083
          ...

```
</details>

-------

| Reason | <code>parallel/test-watch-mode-kill-signal-default</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/60298/](https://ci.nodejs.org/job/node-test-pull-request/69810/), [https://github.com/nodejs/node/pull/59734/](https://ci.nodejs.org/job/node-test-pull-request/69825/), [https://github.com/nodejs/node/pull/60330/](https://ci.nodejs.org/job/node-test-pull-request/69842/)) |
| Appeared | [vm-2xshg](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67493/console), [vm-v9dgt](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67470/console), [test-azure_msft-win10_vs2019-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win10-COMPILED_BY-vs2022_clang/37328/console), [test-azure_msft-win11_vs2022-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-COMPILED_BY-vs2022_clang/37328/console), [test-rackspace-win2019_vs2019-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2019-COMPILED_BY-vs2022_clang/37328/console), [test-rackspace-win2022_vs2022-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2022-COMPILED_BY-vs2022_clang/37328/console), [test-azure_msft-win11_vs2022-arm64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/37328/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69810/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69842/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67493/console">Example</a></summary>

```
not ok 4419 parallel/test-watch-mode-kill-signal-default
  ---
  duration_ms: 120032.20800
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>async-hooks/test-emit-before-on-destroyed</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60298/](https://ci.nodejs.org/job/node-test-pull-request/69810/), [https://github.com/nodejs/node/pull/60385/](https://ci.nodejs.org/job/node-test-pull-request/69885/)) |
| Appeared | [test-ibm-aix72-ppc64_be-2](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59523/console), [test-osuosl-aix72-ppc64_be-4](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59450/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69810/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69885/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59523/console">Example</a></summary>

```
not ok 36 async-hooks/test-emit-before-on-destroyed
  ---
  duration_ms: 429.43900
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:146
      throw error;
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    
    null !== 1
    
        at ChildProcess.<anonymous> (/home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64/test/async-hooks/test-emit-before-on-destroyed.js:56:12)
        at ChildProcess.<anonymous> (/home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64/test/common/index.js:476:15)
        at ChildProcess.emit (node:events:508:28)
        at maybeClose (node:internal/child_process:1085:16)
        at ChildProcess._handle.onexit (node:internal/child_process:304:5) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: null,
      expected: 1,
      operator: 'strictEqual',
      diff: 'simple'
    }
    
    Node.js v26.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-net-connect-abort-controller</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60374/](https://ci.nodejs.org/job/node-test-pull-request/69862/), [https://github.com/nodejs/node/pull/60190/](https://ci.nodejs.org/job/node-test-pull-request/69888/)) |
| Appeared | [test-mnx-smartos23-x64-6](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos23-x64/62945/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69862/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69888/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos23-x64/62945/console">Example</a></summary>

```
not ok 3536 parallel/test-net-connect-abort-controller
  ---
  duration_ms: 300057.61500
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>wpt/test-hr-time</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60271/](https://ci.nodejs.org/job/node-test-pull-request/69803/), [https://github.com/nodejs/node/pull/60367/](https://ci.nodejs.org/job/node-test-pull-request/69856/)) |
| Appeared | [vm-lbl0c](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67506/console), [vm-5wwhg](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67447/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69803/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69856/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67506/console">Example</a></summary>

```
not ok 4811 wpt/test-hr-time
  ---
  duration_ms: 2435.83600
  severity: fail
  exitcode: 1
  stack: |-
    [SKIPPED] idlharness-shadowrealm.window.js: ShadowRealm support is not enabled
    [SKIPPED] window-worker-timeOrigin.window.js: depends on URL.createObjectURL(blob)
    [PASS] self.performance.now() is a function that returns a number
    [PASS] self.performance.now() returns a positive number
    [PASS] self.performance.now() difference is not negative
    [PASS] Performance interface extends EventTarget.
    [PASS] self.performance.now() returns a positive number
    [PASS] self.performance.now() difference is not negative
    [PASS] idl_test validation
    [PASS] Partial interface mixin WindowOrWorkerGlobalScope: original interface mixin defined
    [PASS] Partial interface mixin WindowOrWorkerGlobalScope: member names are unique
    [PASS] Partial interface Window: member names are unique
    [PASS] Window includes GlobalEventHandlers: member names are unique
    [PASS] Window includes WindowEventH...
```
</details>

-------

