Failures in [node-test-pull-request/69670](https://ci.nodejs.org/job/node-test-pull-request/69670/) to [node-test-pull-request/69766](https://ci.nodejs.org/job/node-test-pull-request/69766/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2025-10-17.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2025-10-17 00:11 | 1       | 2       | 33       | 1       | 63      | 2.04%      |


### Jenkins Failure

| Reason | <code>Build timed out (after 30 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59929/](https://ci.nodejs.org/job/node-test-pull-request/69711/), [https://github.com/nodejs/node/pull/60251/](https://ci.nodejs.org/job/node-test-pull-request/69719/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/37263/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69711/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69719/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/37263/console">Example</a></summary>

```
Build timed out (after 30 minutes). Marking the build as failed.
```
</details>

-------


### Build Failure


### JSTest Failure

| Reason | <code>sequential/test-worker-prof</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 19 ([https://github.com/nodejs/node/pull/59876/](https://ci.nodejs.org/job/node-test-pull-request/69675/), [https://github.com/nodejs/node/pull/60131/](https://ci.nodejs.org/job/node-test-pull-request/69676/), [https://github.com/nodejs/node/pull/60206/](https://ci.nodejs.org/job/node-test-pull-request/69689/), [https://github.com/nodejs/node/pull/60062/](https://ci.nodejs.org/job/node-test-pull-request/69691/), [https://github.com/nodejs/node/pull/60223/](https://ci.nodejs.org/job/node-test-pull-request/69694/), [https://github.com/nodejs/node/pull/60225/](https://ci.nodejs.org/job/node-test-pull-request/69696/), [https://github.com/nodejs/node/pull/60142/](https://ci.nodejs.org/job/node-test-pull-request/69702/), [https://github.com/nodejs/node/pull/59929/](https://ci.nodejs.org/job/node-test-pull-request/69711/), [https://github.com/nodejs/node/pull/60251/](https://ci.nodejs.org/job/node-test-pull-request/69731/), [https://github.com/nodejs/node/pull/60256/](https://ci.nodejs.org/job/node-test-pull-request/69732/), [https://github.com/nodejs/node/pull/60255/](https://ci.nodejs.org/job/node-test-pull-request/69733/), [https://github.com/nodejs/node/pull/60205/](https://ci.nodejs.org/job/node-test-pull-request/69735/), [https://github.com/nodejs/node/pull/60250/](https://ci.nodejs.org/job/node-test-pull-request/69750/), [https://github.com/nodejs/node/pull/59873/](https://ci.nodejs.org/job/node-test-pull-request/69752/), [https://github.com/nodejs/node/pull/60269/](https://ci.nodejs.org/job/node-test-pull-request/69756/), [https://github.com/nodejs/node/pull/60266/](https://ci.nodejs.org/job/node-test-pull-request/69757/), [https://github.com/nodejs/node/pull/60276/](https://ci.nodejs.org/job/node-test-pull-request/69759/), [https://github.com/nodejs/node/pull/60244/](https://ci.nodejs.org/job/node-test-pull-request/69765/), [https://github.com/nodejs/node/pull/60217/](https://ci.nodejs.org/job/node-test-pull-request/69766/)) |
| Appeared | [test-azure_msft-win10_vs2019-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win10-COMPILED_BY-vs2022_clang/37301/console), [test-azure_msft-win10_vs2019-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2022_clang/37298/console), [test-azure_msft-win10_vs2019-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2022_clang/37297/console), [test-azure_msft-win11_vs2022-arm64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/37291/console), [test-azure_msft-win11_vs2022-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2022_clang/37276/console), [test-azure_msft-win11_vs2022-arm64-6](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/37254/console), [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/37242/console), [test-azure_msft-win11_vs2022-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-COMPILED_BY-vs2022_clang/37227/console), [test-azure_msft-win11_vs2022-arm64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/37215/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69675/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69766/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win10-COMPILED_BY-vs2022_clang/37301/console">Example</a></summary>

```
not ok 1145 sequential/test-worker-prof
  ---
  duration_ms: 2387.18400
  severity: fail
  exitcode: 1
  stack: |-
    files found in working directory before worker starts [ 'isolate-00000191E144A000-5048-v8.log' ]
    parent prof file: isolate-00000191E144A000-5048-v8.log
    parent posted 45873 messages
    files found in working directory before worker exits [
      'isolate-00000191E144A000-5048-v8.log',
      'isolate-00000191FB1AE000-5048-v8.log'
    ]
    worker prof file: isolate-00000191FB1AE000-5048-v8.log
    
    worker ticks 12
    parent ticks 37
    node:internal/assert/utils:77
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: worker ticks <= 15:
    tick,0x7ff7f143d83e,99028,0,0x0,3,0x191a008297e,0x191a0082607,0x3e19d0d2c7e
    tick,0x7ffad57b7629,176258,0,0x0,0,0x7ff7f149e380,0x24f77005821,0x191a0082a4f,0x191a0082607,0x3e19d0ff55a,0x191a0082a4f,0x191a0082607,0x3e19d0feb23,0x191a0082a4f,0x191a0082607,0x3e19d0fe7b3,0x191a0082a4f,0x191a0082607,0x3e19d0fcc56,0x191a0082a4f,0x...
```
</details>

-------

| Reason | <code>parallel/test-without-async-context-frame</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 16 ([https://github.com/nodejs/node/pull/60175/](https://ci.nodejs.org/job/node-test-pull-request/69674/), [https://github.com/nodejs/node/pull/59876/](https://ci.nodejs.org/job/node-test-pull-request/69675/), [https://github.com/nodejs/node/pull/59929/](https://ci.nodejs.org/job/node-test-pull-request/69716/), [https://github.com/nodejs/node/pull/60251/](https://ci.nodejs.org/job/node-test-pull-request/69719/), [https://github.com/nodejs/node/pull/59896/](https://ci.nodejs.org/job/node-test-pull-request/69721/), [https://github.com/nodejs/node/pull/60255/](https://ci.nodejs.org/job/node-test-pull-request/69733/), [https://github.com/nodejs/node/pull/60250/](https://ci.nodejs.org/job/node-test-pull-request/69746/), [https://github.com/nodejs/node/pull/60271/](https://ci.nodejs.org/job/node-test-pull-request/69754/), [https://github.com/nodejs/node/pull/60272/](https://ci.nodejs.org/job/node-test-pull-request/69755/), [https://github.com/nodejs/node/pull/60266/](https://ci.nodejs.org/job/node-test-pull-request/69757/), [https://github.com/nodejs/node/pull/60278/](https://ci.nodejs.org/job/node-test-pull-request/69761/), [https://github.com/nodejs/node/pull/60205/](https://ci.nodejs.org/job/node-test-pull-request/69762/), [https://github.com/nodejs/node/pull/60254/](https://ci.nodejs.org/job/node-test-pull-request/69763/), [https://github.com/nodejs/node/pull/60256/](https://ci.nodejs.org/job/node-test-pull-request/69764/), [https://github.com/nodejs/node/pull/60244/](https://ci.nodejs.org/job/node-test-pull-request/69765/), [https://github.com/nodejs/node/pull/60217/](https://ci.nodejs.org/job/node-test-pull-request/69766/)) |
| Appeared | [test-digitalocean-ubuntu2404_sharedlibs_container-x64-8](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_shared_x64/53197/console), [vm-gy321](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67409/console), [vm-imm7g](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67408/console), [test-digitalocean-ubuntu2404_sharedlibs_container-x64-9](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_shared_x64/53195/console), [vm-gnhs2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67406/console), [test-digitalocean-ubuntu2404_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_shared_x64/53193/console), [vm-oiqpl](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67401/console), [vm-263lv](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67399/console), [vm-iv9zi](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67388/console), [vm-tn28e](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67387/console), [vm-o3mm0](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67376/console), [vm-qfxrp](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67373/console), [vm-c9pt9](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67372/console), [vm-4ckp1](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67359/console), [vm-36l2p](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67358/console), [vm-gtwyt](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67351/console), [vm-6ll6k](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67295/console), [vm-5tpep](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67294/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69674/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69766/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_shared_x64/53197/console">Example</a></summary>

```
not ok 3960 parallel/test-without-async-context-frame
  ---
  duration_ms: 120075.21900
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-quic-test-client</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 9 ([https://github.com/nodejs/node/pull/60175/](https://ci.nodejs.org/job/node-test-pull-request/69674/), [https://github.com/nodejs/node/pull/60206/](https://ci.nodejs.org/job/node-test-pull-request/69677/), [https://github.com/nodejs/node/pull/59396/](https://ci.nodejs.org/job/node-test-pull-request/69712/), [https://github.com/nodejs/node/pull/59896/](https://ci.nodejs.org/job/node-test-pull-request/69714/), [https://github.com/nodejs/node/pull/60245/](https://ci.nodejs.org/job/node-test-pull-request/69748/), [https://github.com/nodejs/node/pull/60250/](https://ci.nodejs.org/job/node-test-pull-request/69750/), [https://github.com/nodejs/node/pull/60272/](https://ci.nodejs.org/job/node-test-pull-request/69755/), [https://github.com/nodejs/node/pull/60266/](https://ci.nodejs.org/job/node-test-pull-request/69757/), [https://github.com/nodejs/node/pull/60217/](https://ci.nodejs.org/job/node-test-pull-request/69766/)) |
| Appeared | [test-mnx-smartos23-x64-6](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos23-x64/62847/console), [vm-oiqpl](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67401/console), [vm-263lv](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67399/console), [vm-jovkh](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67391/console), [vm-j9sr5](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67389/console), [vm-53pbg](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67349/console), [vm-il0nw](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67347/console), [vm-5tpep](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67297/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69674/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69766/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos23-x64/62847/console">Example</a></summary>

```
not ok 2767 parallel/test-quic-test-client
  ---
  duration_ms: 582.00200
  severity: fail
  exitcode: 1
  stack: |-
    /home/iojs/build/workspace/node-test-commit-smartos/nodes/smartos23-x64/out/Release/ngtcp2_test_client
    node:internal/modules/run_main:107
        triggerUncaughtException(
        ^
    
    AssertionError [ERR_ASSERTION]: Missing expected rejection.
        at process.processTicksAndRejections (node:internal/process/task_queues:103:5)
        at async file:///home/iojs/build/workspace/node-test-commit-smartos/nodes/smartos23-x64/test/parallel/test-quic-test-client.mjs:36:1 {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      actual: undefined,
      expected: { message: /Process exited with code 1 and signal null/ },
      operator: 'rejects',
      diff: 'simple'
    }
    
    Node.js v26.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-runner-output</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 9 ([https://github.com/nodejs/node/pull/60208/](https://ci.nodejs.org/job/node-test-pull-request/69679/), [https://github.com/nodejs/node/pull/60131/](https://ci.nodejs.org/job/node-test-pull-request/69688/), [https://github.com/nodejs/node/pull/60251/](https://ci.nodejs.org/job/node-test-pull-request/69719/), [https://github.com/nodejs/node/pull/60217/](https://ci.nodejs.org/job/node-test-pull-request/69720/), [https://github.com/nodejs/node/pull/60236/](https://ci.nodejs.org/job/node-test-pull-request/69723/), [https://github.com/nodejs/node/pull/60255/](https://ci.nodejs.org/job/node-test-pull-request/69724/), [https://github.com/nodejs/node/pull/59896/](https://ci.nodejs.org/job/node-test-pull-request/69728/), [https://github.com/nodejs/node/pull/60245/](https://ci.nodejs.org/job/node-test-pull-request/69741/), [https://github.com/nodejs/node/pull/60205/](https://ci.nodejs.org/job/node-test-pull-request/69762/)) |
| Appeared | [vm-gnhs2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67406/console), [undefined](https://ci.nodejs.org/job/node-test-commit-custom-suites-freestyle/44412/console), [vm-wi81c](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67356/console), [test-ibm-rhel9-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel9-x64/66985/console), [vm-utd49](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67361/console), [test-azure_msft-win11_vs2022-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2022_clang/37263/console), [test-digitalocean-alpine321_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/66977/console), [vm-ptrav](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67307/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69679/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69762/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67406/console">Example</a></summary>

```
not ok 2761 parallel/test-runner-output
  ---
  duration_ms: 16679.80300
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'test-runner/output/test-timeout-flag.js'
    Location: test/parallel/test-runner-output.mjs:356:5
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    + actual - expected
    ... Skipped lines
    
      'TAP version 13\n' +
        '# Subtest: --test-timeout is set to 100ms\n' +
        '    # Subtest: should timeout after 100ms\n' +
        '    not ok 1 - should timeout after 100ms\n' +
        '      ---\n' +
    ...

```
</details>

-------

| Reason | <code>parallel/test-runner-watch-mode-kill-signal</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 9 ([https://github.com/nodejs/node/pull/60175/](https://ci.nodejs.org/job/node-test-pull-request/69674/), [https://github.com/nodejs/node/pull/60168/](https://ci.nodejs.org/job/node-test-pull-request/69681/), [https://github.com/nodejs/node/pull/60199/](https://ci.nodejs.org/job/node-test-pull-request/69682/), [https://github.com/nodejs/node/pull/60062/](https://ci.nodejs.org/job/node-test-pull-request/69698/), [https://github.com/nodejs/node/pull/59983/](https://ci.nodejs.org/job/node-test-pull-request/69707/), [https://github.com/nodejs/node/pull/60217/](https://ci.nodejs.org/job/node-test-pull-request/69720/), [https://github.com/nodejs/node/pull/60256/](https://ci.nodejs.org/job/node-test-pull-request/69736/), [https://github.com/nodejs/node/pull/60205/](https://ci.nodejs.org/job/node-test-pull-request/69762/), [https://github.com/nodejs/node/pull/60244/](https://ci.nodejs.org/job/node-test-pull-request/69765/)) |
| Appeared | [vm-gy321](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67409/console), [vm-gnhs2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67406/console), [vm-se52j](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67377/console), [test-digitalocean-alpine321_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/66984/console), [test-azure-ubuntu2204_container-arm64-6](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/20696/console), [vm-lkfp1](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67342/console), [vm-x37tr](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67326/console), [vm-yx2lw](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67304/console), [vm-i57a3](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67303/console), [vm-5tpep](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67294/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69674/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69765/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67409/console">Example</a></summary>

```
not ok 3256 parallel/test-runner-watch-mode-kill-signal
  ---
  duration_ms: 120099.61500
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>sequential/test-perf-hooks</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/60131/](https://ci.nodejs.org/job/node-test-pull-request/69688/), [https://github.com/nodejs/node/pull/60256/](https://ci.nodejs.org/job/node-test-pull-request/69736/), [https://github.com/nodejs/node/pull/60245/](https://ci.nodejs.org/job/node-test-pull-request/69744/), [https://github.com/nodejs/node/pull/60269/](https://ci.nodejs.org/job/node-test-pull-request/69756/), [https://github.com/nodejs/node/pull/60205/](https://ci.nodejs.org/job/node-test-pull-request/69762/)) |
| Appeared | [vm-gnhs2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67406/console), [vm-l4ydv](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67400/console), [vm-iv9zi](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67385/console), [vm-se52j](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67377/console), [vm-o3mm0](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67376/console), [test-digitalocean-ubuntu2404_sharedlibs_container-x64-10](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_openssl30_x64/53163/console), [vm-1uzqj](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67313/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69688/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69762/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67406/console">Example</a></summary>

```
not ok 4771 sequential/test-perf-hooks
  ---
  duration_ms: 834.75200
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:77
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: Date.now() - performance.timeOrigin (248.912109375) - process.uptime() * 1000 (87.691226) = 161.220883375 >= +- 50
        at Object.<anonymous> (/Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/sequential/test-perf-hooks.js:36:3)
        at Module._compile (node:internal/modules/cjs/loader:1760:14)
        at Object..js (node:internal/modules/cjs/loader:1892:10)
        at Module.load (node:internal/modules/cjs/loader:1480:32)
        at Module._load (node:internal/modules/cjs/loader:1299:12)
        at TracingChannel.traceSync (node:diagnostics_channel:328:14)
        at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
        at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
        at node:internal/main/run_main_module:33:47 {
...
```
</details>

-------

| Reason | <code>wpt/test-hr-time</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/59929/](https://ci.nodejs.org/job/node-test-pull-request/69716/), [https://github.com/nodejs/node/pull/59896/](https://ci.nodejs.org/job/node-test-pull-request/69728/), [https://github.com/nodejs/node/pull/60261/](https://ci.nodejs.org/job/node-test-pull-request/69734/), [https://github.com/nodejs/node/pull/60266/](https://ci.nodejs.org/job/node-test-pull-request/69757/)) |
| Appeared | [vm-oiqpl](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67401/console), [vm-ztsar](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67374/console), [vm-4jmql](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67366/console), [vm-gtwyt](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67351/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69716/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69757/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67401/console">Example</a></summary>

```
not ok 4826 wpt/test-hr-time
  ---
  duration_ms: 2288.00300
  severity: fail
  exitcode: 1
  stack: |-
    [SKIPPED] idlharness-shadowrealm.window.js: ShadowRealm support is not enabled
    [SKIPPED] window-worker-timeOrigin.window.js: depends on URL.createObjectURL(blob)
    [PASS] self.performance.now() is a function that returns a number
    [PASS] self.performance.now() returns a positive number
    [PASS] self.performance.now() difference is not negative
    [PASS] Performance interface extends EventTarget.
    [PASS] self.performance.now() returns a positive number
    [PASS] self.performance.now() difference is not negative
    [PASS] idl_test validation
    [PASS] Partial interface mixin WindowOrWorkerGlobalScope: original interface mixin defined
    [PASS] Partial interface mixin WindowOrWorkerGlobalScope: member names are unique
    [PASS] Partial interface Window: member names are unique
    [PASS] Window includes GlobalEventHandlers: member names are unique
    [PASS] Window includes WindowEventH...
```
</details>

-------

| Reason | <code>parallel/test-http2-close-while-writing</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/60175/](https://ci.nodejs.org/job/node-test-pull-request/69674/), [https://github.com/nodejs/node/pull/60199/](https://ci.nodejs.org/job/node-test-pull-request/69682/), [https://github.com/nodejs/node/pull/60217/](https://ci.nodejs.org/job/node-test-pull-request/69720/)) |
| Appeared | [vm-36l2p](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67358/console), [vm-yx2lw](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67304/console), [vm-5tpep](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67294/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69674/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69720/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67358/console">Example</a></summary>

```
not ok 2135 parallel/test-http2-close-while-writing
  ---
  duration_ms: 120065.32700
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>client-proxy/test-https-proxy-request-invalid-char-in-url</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59896/](https://ci.nodejs.org/job/node-test-pull-request/69721/), [https://github.com/nodejs/node/pull/60250/](https://ci.nodejs.org/job/node-test-pull-request/69738/)) |
| Appeared | [vm-cmeeo](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67379/console), [vm-4ckp1](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67359/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69721/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69738/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67379/console">Example</a></summary>

```
not ok 4379 client-proxy/test-https-proxy-request-invalid-char-in-url
  ---
  duration_ms: 1508.61200
  severity: fail
  exitcode: 1
  stack: |-
    [Upstream server] responding to request for '/newline-in-host'
    [Upstream server] responding to request for '/carriage-return-in-host'
    [Proxy client] Received response from server for 'https://local\nhost:55410/newline-in-host': Response for '/newline-in-host'
    [Proxy client] #1 closed request for: 'https://local\nhost:55410/newline-in-host'
    [Proxy client] Received response from server for 'https://local\rhost:55410/carriage-return-in-host': Response for '/carriage-return-in-host'
    [Proxy client] #2 closed request for: 'https://local\rhost:55410/carriage-return-in-host'
    [Upstream server] responding to request for '/carriage-return-in-port'
    [Upstream server] responding to request for '/crlf-in-host'
    [Upstream server] responding to request for '/newline-in-port'
    [Upstream server] responding to request for '/crlf-in-port'
    [Proxy ...
```
</details>

-------

| Reason | <code>parallel/test-gc-http-client-connaborted</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60142/](https://ci.nodejs.org/job/node-test-pull-request/69705/), [https://github.com/nodejs/node/pull/59873/](https://ci.nodejs.org/job/node-test-pull-request/69752/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/37285/console), [test-azure_msft-win11_vs2022-arm64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/37247/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69705/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69752/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/37285/console">Example</a></summary>

```
not ok 410 parallel/test-gc-http-client-connaborted
  ---
  duration_ms: 497.99900
  severity: fail
  exitcode: 3221226505
  stack: |-
  ...

```
</details>

-------

